//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package tls

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *API) DeepCopyInto(out *API) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new API.
func (in *API) DeepCopy() *API {
	if in == nil {
		return nil
	}
	out := new(API)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDB) DeepCopyInto(out *APIDB) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.DB.DeepCopyInto(&out.DB)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDB.
func (in *APIDB) DeepCopy() *APIDB {
	if in == nil {
		return nil
	}
	out := new(APIDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDBMessaging) DeepCopyInto(out *APIDBMessaging) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.DB.DeepCopyInto(&out.DB)
	in.Messaging.DeepCopyInto(&out.Messaging)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDBMessaging.
func (in *APIDBMessaging) DeepCopy() *APIDBMessaging {
	if in == nil {
		return nil
	}
	out := new(APIDBMessaging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIMessaging) DeepCopyInto(out *APIMessaging) {
	*out = *in
	in.API.DeepCopyInto(&out.API)
	in.Messaging.DeepCopyInto(&out.Messaging)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIMessaging.
func (in *APIMessaging) DeepCopy() *APIMessaging {
	if in == nil {
		return nil
	}
	out := new(APIMessaging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIService) DeepCopyInto(out *APIService) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = make(map[service.Endpoint]GenericService, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIService.
func (in *APIService) DeepCopy() *APIService {
	if in == nil {
		return nil
	}
	out := new(APIService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ca) DeepCopyInto(out *Ca) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ca.
func (in *Ca) DeepCopy() *Ca {
	if in == nil {
		return nil
	}
	out := new(Ca)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DB) DeepCopyInto(out *DB) {
	*out = *in
	in.DB.DeepCopyInto(&out.DB)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DB.
func (in *DB) DeepCopy() *DB {
	if in == nil {
		return nil
	}
	out := new(DB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMessaging) DeepCopyInto(out *DBMessaging) {
	*out = *in
	in.DB.DeepCopyInto(&out.DB)
	in.Messaging.DeepCopyInto(&out.Messaging)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMessaging.
func (in *DBMessaging) DeepCopy() *DBMessaging {
	if in == nil {
		return nil
	}
	out := new(DBMessaging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBService) DeepCopyInto(out *DBService) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBService.
func (in *DBService) DeepCopy() *DBService {
	if in == nil {
		return nil
	}
	out := new(DBService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericService) DeepCopyInto(out *GenericService) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.IssuerName != nil {
		in, out := &in.IssuerName, &out.IssuerName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericService.
func (in *GenericService) DeepCopy() *GenericService {
	if in == nil {
		return nil
	}
	out := new(GenericService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Messaging) DeepCopyInto(out *Messaging) {
	*out = *in
	in.Messaging.DeepCopyInto(&out.Messaging)
	out.Ca = in.Ca
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Messaging.
func (in *Messaging) DeepCopy() *Messaging {
	if in == nil {
		return nil
	}
	out := new(Messaging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingService) DeepCopyInto(out *MessagingService) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingService.
func (in *MessagingService) DeepCopy() *MessagingService {
	if in == nil {
		return nil
	}
	out := new(MessagingService)
	in.DeepCopyInto(out)
	return out
}
